[package]
name = "rdf-star-presidents"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "4.0", features = ["derive"] }
rio_api = "0.8"
rio_turtle = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
