name: release

on:
  push:
    branches:
    - release*
    tags:
    - 'v*'

env:
  # The NAME makes it easier to copy/paste snippets from other CI configs
  NAME: rdf-star-presidents

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run
      run: |
        cargo run -q > rdf-star-presidents.nt

    - uses: ncipollo/release-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        artifacts: "rdf-star-presidents.nt"
        artifactErrorsFailBuild: true
        body: "See [CHANGELOG.md](https://github.com/langston-barrett/rdf-star-presidents/blob/main/CHANGELOG.md)"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
